FROM ruby:2.1.2

RUN gem install sass

# L'exécutable que nous souhaitons faire tourner dans le conteneur
ENTRYPOINT ["sass"]

# Vous pouvez définir des options par défaut pour "sass" avec CMD
# CMD ["--watch", "/app/"]
